name: Hospital Management CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix client
      - run: npm install --prefix server
      - run: |
         cd server
         touch .env
         echo "${{secrets.PROD_ENV}}" > .env 
      - run: |
         cd server
         pm2 restart HospitalManagement
