name: Hospital Management CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['4.4']
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install --prefix client
      - run: npm run build --prefix client
      - run: npm install
      - run: |
         touch .env
         echo "${{secrets.MONGO_URL}}" > .env
         echo "${{secrets.SECRET}}" > .env
         echo "${{secrets.TOKEN_EXPIRY_TIME}}" > .env
         echo "${{secrets.PORT}}" > .env
     
