name: Hospital Management CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t nikitasimform/hospital-management  .
      - name: Publish Image to docker hub
        run: docker push nikitasimform/hospital-management:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull nikitasimform/hospital-management:latest
      - name: Delete old container
        run: docker rm -f hospital-management-container
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name hospital-management-container -e MONGO_URL='${{ secrets.MONGO_URL }}' -e TOKEN_EXPIRY_TIME='${{ secrets.TOKEN_EXPIRY_TIME }}'  -e SECRET='${{ secrets.SECRET }}' integrationninjas/nodejs-app
